export const BRAND_DOMAINS: Record<string, string> = {
  // OTT / Entertainment / Subscriptions / Social
  netflix: "netflix.com",
  spotify: "spotify.com",
  youtube: "youtube.com",
  yt: "youtube.com",
  disney: "disneyplus.com",
  hulu: "hulu.com",
  prime: "amazon.com",
  hbo: "hbo.com",
  hotstar: "hotstar.com",
  altbalaji: "altbalaji.com",
  jiocinema: "jiocinema.com",
  sony: "sonyliv.com",
  crunchyroll: "crunchyroll.com",
  mubi: "mubi.com",
  voot: "voot.com",
  zee5: "zee5.com",
  gaana: "gaana.com",
  wynk: "wynk.in",
  mxplayer: "mxplayer.in",
  audible: "audible.com",
  peacock: "peacocktv.com",
  paramount: "paramountplus.com",
  twitch: "twitch.tv",
  vimeo: "vimeo.com",
  discord: "discord.com",
  instagram: "instagram.com",
  facebook: "facebook.com",
  fb: "facebook.com",
  snapchat: "snapchat.com",
  twitter: "twitter.com",
  patreon: "patreon.com",
  onlyfans: "onlyfans.com",
  koo: "kooapp.com",
  apple: "apple.com",

  // Food / Dining / Delivery / Cafes
  swiggy: "swiggy.com",
  zomato: "zomato.com",
  ubereats: "ubereats.com",
  domino: "dominos.com",
  pizzahut: "pizzahut.com",
  mcdonald: "mcdonalds.com",
  kfc: "kfc.com",
  burgerking: "burgerking.com",
  subway: "subway.com",
  tacobell: "tacobell.com",
  starbuck: "starbucks.com",
  dunkin: "dunkindonuts.com",
  "cafe coffee day": "cafecoffeeday.com",
  ccd: "cafecoffeeday.com",
  barista: "barista.co.in",
  "chai point": "chaipoint.com",
  chaayos: "chaayos.com",
  "third wave": "thirdwavecoffeeroasters.com",
  "blue tokai": "bluetokaicoffee.com",
  theobroma: "theobroma.in",
  "belgian waffle": "belgianwaffle.in",
  "mad over donuts": "madoverdonuts.com",
  bikanervala: "bikanervala.com",
  faasos: "faasos.com",
  behrouz: "behrouzbiryani.com",
  freshmenu: "freshmenu.com",
  eatsure: "eatsure.com",
  eatfit: "eatfit.in",
  box8: "box8.in",
  "mojo pizza": "mojopizza.in",
  "oven story": "ovenstory.in",
  "wow china": "wowchina.com",
  "wow momo": "wowmomo.com",
  "wow chicken": "wowchicken.com",
  "barbeque nation": "barbequenation.com",
  haldiram: "haldirams.com",
  a2b: "a2b.in",
  "saravana bhavan": "saravanabhavan.com",
  truffles: "truffles.co.in",
  "cream stone": "creamstoneicecream.com",
  "baskin robbins": "baskinrobbinsindia.com",
  naturals: "naturalicecreams.in",
  "nic ice cream": "nicicecreams.com",
  giani: "gianisicecream.com",

  // Shopping / E-commerce / D2C / Electronics
  amazon: "amazon.com",
  flipkart: "flipkart.com",
  myntra: "myntra.com",
  ajio: "ajio.com",
  meesho: "meesho.com",
  nykaa: "nykaa.com",
  cliq: "tatacliq.com",
  reliance: "reliancedigital.in",
  "reliance smart": "reliancesmart.in",
  croma: "croma.com",
  dmart: "dmartindia.com",
  "big bazaar": "bigbazaar.com",
  spencer: "spencers.in",
  ikea: "ikea.com",
  decathlon: "decathlon.com",
  pepperfry: "pepperfry.com",
  firstcry: "firstcry.com",
  snapdeal: "snapdeal.com",
  shopclues: "shopclues.com",
  ebay: "ebay.com",
  etsy: "etsy.com",
  aliexpress: "aliexpress.com",
  "vishal mega mart": "vishalmegamart.com",
  "more retail": "moreretail.in",
  easyday: "easyday.in",
  spar: "sparindia.com",
  lulu: "luluhypermarket.com",
  samsung: "samsung.com",
  oneplus: "oneplus.com",
  xiaomi: "mi.com",
  realme: "realme.com",
  boat: "boat-lifestyle.com",
  noise: "gonoise.com",
  "fire boltt": "fireboltt.com",
  hp: "hp.com",
  dell: "dell.com",
  lenovo: "lenovo.com",
  zara: "zara.com",
  zudio: "tata.com",
  westside: "tata.com",
  nike: "nike.com",
  adidas: "adidas.com",
  puma: "puma.com",
  levi: "levi.com",
  "allen solly": "allensolly.com",
  "van heusen": "vanheusen.com",

  // Banking / Wallets / Fintech / BNPL
  hdfc: "hdfcbank.com",
  icici: "icicibank.com",
  sbi: "sbi.co.in",
  axis: "axisbank.com",
  kotak: "kotak.com",
  idfc: "idfcfirstbank.com",
  "yes bank": "yesbank.in",
  rbl: "rblbank.com",
  indusind: "indusind.com",
  bandhan: "bandhanbank.com",
  hsbc: "hsbc.co.in",
  "standard chartered": "sc.com",
  citi: "citibank.co.in",
  amex: "americanexpress.com",
  paytm: "paytm.com",
  phonepe: "phonepe.com",
  gpay: "google.com",
  "amazon pay": "amazon.com",
  bharatpe: "bharatpe.com",
  mobikwik: "mobikwik.com",
  freecharge: "freecharge.in",
  kreditbee: "kreditbee.in",
  moneytap: "moneytap.com",
  zestmoney: "zestmoney.in",
  cashe: "cashe.co.in",
  paysense: "gopaysense.com",
  fibe: "fibe.in",
  navi: "navi.com",
  kissht: "kissht.com",
  cred: "cred.club",
  slice: "sliceit.com",
  onecard: "getonecard.com",
  lazypay: "lazypay.in",
  simpl: "getsimpl.com",
  rupay: "rupay.co.in",
  visa: "visa.com",
  mastercard: "mastercard.com",

  // Bills / Utilities / Daily Services
  airtel: "airtel.in",
  jio: "jio.com",
  jiofiber: "jio.com",
  "airtel xstream": "airtel.in",
  "bsnl fiber": "bsnl.co.in",
  jiomart: "jiomart.com",
  vi: "myvi.in",
  bsnl: "bsnl.co.in",
  act: "actcorp.in",
  hathway: "hathway.com",
  "tata power": "tatapower.com",
  adani: "adanipower.com",
  bescom: "bescom.co.in",
  "sun direct": "sundirect.in",
  dishtv: "dishtv.in",
  tataplay: "tataplay.com",
  kent: "kent.co.in",
  livpure: "livpure.com",
  "eureka forbes": "eurekaforbes.com",
  "urban ladder": "urbanladder.com",
  godrej: "godrej.com",
  lg: "lg.com",

  // Transport / Mobility / Travel / Airlines
  uber: "uber.com",
  ola: "olacabs.com",
  rapido: "rapido.com",
  redbus: "redbus.in",
  abhibus: "abhibus.com",
  yulu: "yulu.buy",
  bounce: "bounceshare.com",
  vogo: "vogo.in",
  parkplus: "parkplus.io",
  fastag: "ihmcl.co.in",
  "ola electric": "olaelectric.com",
  ather: "atherenergy.com",
  irctc: "irctc.co.in",
  confirmtkt: "confirmtkt.com",
  railyatri: "railyatri.in",
  blablacar: "blablacar.in",
  "namma metro": "bmrc.co.in",
  "delhi metro": "delhimetrorail.com",
  // Airlines (Added variations)
  indigo: "goindigo.in",
  "air india": "airindia.com",
  airindia: "airindia.com",
  spicejet: "spicejet.com",
  vistara: "airvistara.com",
  akasa: "akasaair.com",
  airasia: "airasia.com",
  "air asia": "airasia.com",
  emirates: "emirates.com",
  "qatar airways": "qatarairways.com",
  qatar: "qatarairways.com",
  "singapore airlines": "singaporeair.com",
  singapore: "singaporeair.com",
  lufthansa: "lufthansa.com",
  "british airways": "britishairways.com",
  british: "britishairways.com",
  "thai airways": "thaiairways.com",
  thai: "thaiairways.com",
  etihad: "etihad.com",
  qantas: "qantas.com",
  turkish: "turkishairlines.com",
  cathay: "cathaypacific.com",
  makemytrip: "makemytrip.com",
  mmt: "makemytrip.com",
  goibibo: "goibibo.com",
  cleartrip: "cleartrip.com",
  yatra: "yatra.com",
  agoda: "agoda.com",
  skyscanner: "skyscanner.net",
  "vfs global": "vfsglobal.com",
  oyo: "oyorooms.com",
  treebo: "treebo.com",
  fabhotels: "fabhotels.com",
  taj: "tajhotels.com",
  itc: "itchotels.com",
  marriott: "marriott.com",
  hilton: "hilton.com",
  hyatt: "hyatt.com",
  airbnb: "airbnb.com",
  zoomcar: "zoomcar.com",
  revv: "revv.co.in",
  drivezy: "drivezy.com",
  "quick ride": "quickride.in",
  "indian oil": "iocl.com",
  iocl: "iocl.com",
  bpcl: "bharatpetroleum.in",
  hpcl: "hpcl.co.in",
  "hp petrol": "hpcl.co.in",
  petrol: "shell.com",
  shell: "shell.com",
  nayara: "nayaraenergy.com",
  avis: "avis.com",
  hertz: "hertz.com",
  turo: "turo.com",

  // Travel Extras / Forex
  "thomas cook": "thomascook.in",
  sotc: "sotc.in",
  "cox & kings": "coxandkings.com",
  "western union": "westernunion.com",
  moneygram: "moneygram.com",
  bookmyforex: "bookmyforex.com",
  wise: "wise.com",

  // Quick Commerce / Hyperlocal / Services
  blinkit: "blinkit.com",
  zepto: "zepto.com",
  bigbasket: "bigbasket.com",
  instamart: "swiggy.com",
  dunzo: "dunzo.com",
  justdial: "justdial.com",
  sulekha: "sulekha.com",
  quikr: "quikr.com",
  olx: "olx.in",
  bro4u: "bro4u.com",

  // Investments / Wealth / Gold
  zerodha: "zerodha.com",
  kite: "zerodha.com",
  groww: "groww.in",
  upstox: "upstox.com",
  "angel one": "angelone.in",
  "paytm money": "paytmmoney.com",
  "et money": "etmoney.com",
  kuvera: "kuvera.in",
  indmoney: "indmoney.com",
  coinswitch: "coinswitch.co",
  wazirx: "wazirx.com",
  binance: "binance.com",
  coinbase: "coinbase.com",
  fidelity: "fidelity.com",
  vanguard: "vanguard.com",
  robinhood: "robinhood.com",
  etoro: "etoro.com",
  schwab: "schwab.com",
  "td ameritrade": "tdameritrade.com",
  "interactive brokers": "interactivebrokers.com",
  "tanishq": "tanishq.co.in",
  "mmtc pamp": "mmtcpamp.com",
  augmont: "augmont.com",
  safegold: "safegold.com",
  scripbox: "scripbox.com",
  wealthy: "wealthy.in",

  // Health / Pharmacy / Insurance / Wellness
  apollo: "apollo247.com",
  practo: "practo.com",
  "1mg": "1mg.com",
  netmeds: "netmeds.com",
  pharmeasy: "pharmeasy.in",
  medplus: "medplusmart.com",
  fortis: "fortishealthcare.com",
  max: "maxhealthcare.in",
  manipal: "manipalhospitals.com",
  columbia: "columbiaasia.com",
  care: "carehospitals.com",
  thyrocare: "thyrocare.com",
  metropolis: "metropolisindia.com",
  srl: "srlworld.com",
  "dr lal pathlabs": "lalpathlabs.com",
  lic: "licindia.in",
  "hdfc life": "hdfclife.com",
  "icici prudential": "iciciprulife.com",
  "star health": "starhealth.in",
  religare: "religarehealthinsurance.com",
  "niva bupa": "nivabupa.com",
  "max bupa": "nivabupa.com",
  headspace: "headspace.com",
  calm: "calm.com",

  // Education / Learning
  byju: "byjus.com",
  unacademy: "unacademy.com",
  coursera: "coursera.org",
  udemy: "udemy.com",
  vedantu: "vedantu.com",
  toppr: "toppr.com",
  doubtnut: "doubtnut.com",
  skillshare: "skillshare.com",
  edx: "edx.org",
  simplilearn: "simplilearn.com",
  scaler: "scaler.com",
  "newton school": "newtonschool.co",
  "great learning": "greatlearning.in",
  upgrad: "upgrad.com",
  internshala: "internshala.com",
  "khan academy": "khanacademy.org",
  upsc: "upsc.gov.in",
  ssc: "ssc.gov.in",
  nta: "nta.ac.in",
  "tcs ion": "tcsion.com",
  duolingo: "duolingo.com",
  udacity: "udacity.com",
  pluralsight: "pluralsight.com",
  "whitehat jr": "whitehatjr.com",
  "physics wallah": "pw.live",
  testbook: "testbook.com",
  adda247: "adda247.com",
  gradeup: "byjus.com",
  cuemath: "cuemath.com",
  brainly: "brainly.in",

  // Gaming
  steam: "steampowered.com",
  playstation: "playstation.com",
  xbox: "xbox.com",
  epic: "epicgames.com",
  garena: "garena.com",
  googleplay: "play.google.com",
  riot: "riotgames.com",
  ubisoft: "ubisoft.com",
  ea: "ea.com",
  nintendo: "nintendo.com",
  roblox: "roblox.com",
  blizzard: "blizzard.com",
  supercell: "supercell.com",
  dream11: "dream11.com",
  mpl: "mpl.live",
  winzo: "winzogames.com",
  "paytm first games": "paytmfirstgames.com",
  "ludo king": "ludoking.com",

  // Developer / Hosting / Tech
  microsoft: "microsoft.com",
  workspace: "google.com",
  github: "github.com",
  gitlab: "gitlab.com",
  digitalocean: "digitalocean.com",
  heroku: "heroku.com",
  vercel: "vercel.com",
  netlify: "netlify.com",
  slack: "slack.com",
  zoom: "zoom.us",
  notion: "notion.so",
  dropbox: "dropbox.com",
  adobe: "adobe.com",
  canva: "canva.com",
  figma: "figma.com",
  aws: "amazon.com",
  azure: "microsoft.com",
  salesforce: "salesforce.com",
  hubspot: "hubspot.com",
  zoho: "zoho.com",
  freshworks: "freshworks.com",

  // Home / Rent / Real Estate / Services
  "urban company": "urbancompany.com",
  nobroker: "nobroker.in",
  magicbricks: "magicbricks.com",
  "99acres": "99acres.com",
  housing: "housing.com",
  housejoy: "housejoy.in",
  rentomojo: "rentomojo.com",
  nestaway: "nestaway.com",
  "zolo stays": "zolostays.com",
  colive: "colive.com",
  "square yards": "squareyards.com",
  proptiger: "proptiger.com",

  // Logistics & Delivery
  delhivery: "delhivery.com",
  "blue dart": "bluedart.com",
  dtdc: "dtdc.in",
  "india post": "indiapost.gov.in",
  "ecom express": "ecomexpress.in",
  xpressbees: "xpressbees.com",
  fedex: "fedex.com",
  dhl: "dhl.com",
  ups: "ups.com",
  aramex: "aramex.com",
  shadowfax: "shadowfax.in",
  ekart: "ekartlogistics.com",

  // Lifestyle / Fashion / Beauty / Fitness
  "cult fit": "cult.fit",
  "gold's gym": "goldsgym.in",
  healthifyme: "healthifyme.com",
  fittr: "fittr.com",
  "sarva yoga": "sarva.com",
  bookmyshow: "bookmyshow.com",
  lenskart: "lenskart.com",
  titan: "titan.co.in",
  fastrack: "fastrack.in",
  sephora: "sephora.com",
  purplle: "purplle.com",
  mamaearth: "mamaearth.in",
  lakme: "lakmeindia.com",
  "forest essentials": "forestessentialsindia.com",
  sugar: "sugarcosmetics.com",
  beardo: "beardo.in",
  "bombay shaving company": "bombayshavingcompany.com",
  ustraa: "ustraa.com",
  "wow skin science": "buywow.in",
  "under armour": "underarmour.com",
  fitbit: "fitbit.com",
  myfitnesspal: "myfitnesspal.com",
  healthkart: "healthkart.com",
};

export function getBrandIconData(description: string): { domain: string, url: string } | null {
  if (!description) return null;
  const desc = description.toLowerCase().trim();
  
  // Try to find the best match by checking if the description contains the brand key
  // We sort by length descending to match more specific brands first (e.g. "air india" before "air")
  const sortedKeys = Object.keys(BRAND_DOMAINS).sort((a, b) => b.length - a.length);

  for (const key of sortedKeys) {
    if (desc.includes(key)) {
      const domain = BRAND_DOMAINS[key];
      return {
        domain,
        url: `https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://${domain}&size=128`
      };
    }
  }
  return null;
}

export function getBrandIcon(description: string): string | null {
  const data = getBrandIconData(description);
  return data ? data.url : null;
}
